# Generated by Django 5.2.9 on 2026-01-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
